"diagnostic" = { underline = { color = "#EECC88", style = "curl" } }
"diagnostic.error" = { underline = { color = "#BB6666", style = "curl" } }
"diagnostic.hint" = { underline = { color = "#0099CC", style = "curl" } }
"diagnostic.info" = { underline = { color = "#88C0D0", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#EECC88", style = "curl" } }

"error" = "#BB6666"
"hint" = "#0099CC"
"info" = "#88C0D0"
"warning" = "#EECC88"

"diff.delta" = "#EECC88"
"diff.minus" = "#BB6666"
"diff.plus" = "#00CC00"

"git.delta.moved" = "#0055CC"

"ui.background" = { bg = "#002030", fg = "#405060" }
"ui.background.separator" = { fg = "#305070" }
"ui.text" = "#90A0B0"
"ui.text.focus" = { bg = "#003060", fg = "#0090D0" }
"ui.window" = "#3b4252"

"ui.debug.active" = "#EECC88"
"ui.debug.breakpoint" = "#BB6666"

"ui.menu" = { bg = "#001020", fg = "#6090B0" }
"ui.menu.scroll" = { fg = "#0099CC", bg = "#6090B0" }
"ui.menu.selected" = { fg = "#88C0D0", bg = "#404860" }
"ui.popup" = { bg = "#001020", fg="#6090B0" }
"ui.popup.info" = { bg = "#001020", fg="#6090B0" }
"ui.help" = { bg = "#001020", fg="#6090B0" }

"ui.gutter" = "#00CCCC"
"ui.linenr" = "#505870"
"ui.linenr.selected" = "#00CCCC"

"ui.cursor" = { fg = "#0099CC", bg = "#003040" }
"ui.cursorcolumn.primary" = { bg = "#003040", fg = "#DDDD00" }
"ui.cursorline.primary" = { bg = "#003040" }

"ui.selection" = { bg = "#004050", fg = "#00AACC" }
"ui.highlight" = { fg = "#88C0D0", bg = "#404860" }

"ui.statusline" = { bg = "#001820", fg = "#8090A0" }
"ui.statusline.inactive" = { bg = "#101010", fg = "#406080" }
"ui.statusline.insert" = { bg = "#006666", fg = "#00CCCC" }
"ui.statusline.normal" = { bg = "#000010", fg = "#406080" }
"ui.statusline.select" = { bg = "#006000", fg = "#00CC00" }
"ui.statusline.separator" = "#204060"

"ui.virtual.indent-guide" = "#505870"
"ui.virtual.inlay-hint" = { fg = "#505870", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "#BB6666", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "#3b4252" }
"ui.virtual.whitespace" = "#505870"
"ui.virtual.wrap" = "#505870"

"ui.bufferline" = { fg = "#00CCCC", bg = "#3b4252" }
"ui.bufferline.active" = { fg = "#00CC00", bg = "#404860", underline = { color = "#88C0D0", style = "line" }, modifiers = [ "italic" ] }

"markup.heading" = "##88C0D0"
"markup.list" = "#80A0C0"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.text" = "#88C0D0"
"markup.raw" = "#90BBBB"
