"type" = { fg = "#00A0C0" }
"constructor" = { fg = "#0088E0" }
"constant" = { fg = "#AABBCC" }
"string" = "#6080A0"
"string.regexp" = { bg = "#003080", fg = "#8090A0" }
"string.special" = "#CCCC00"
"comment" = "#607080"
"variable" = { fg = "#0080C0" }
"variable.parameter" = { fg = "#0080C0" }
"variable.builtin" = { fg = "#00AADD" }
"label" = "#CCCC00"
"keyword" = { fg = "#6080A0" }
"operator" = { fg = "#8090A0" }
"punctuation" = { fg = "#8090A0" }
"function" = { fg = "#9070D0" }
"tag" = { fg = "#778899" }
"attribute" = "#DDDD00"
"namespace" = { fg = "#00CCAA" }
"special" = "#00CCAA"

"ui.background" = { bg = "#000818", fg = "#708090" }
"ui.text" = { fg = "default_fg", modifiers = ["bold"] }

"ui.statusline" = { fg = "#606070", bg = "#000818" }
"ui.statusline.inactive" = { bg = "#101010", fg = "#406080" }
"ui.statusline.insert" = { bg = "#006666", fg = "#00CCCC", modifiers = ["bold"] }
"ui.statusline.normal" = { bg = "#000010", fg = "#406080", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "#006000", fg = "#00CC00", modifiers = ["bold"] }

"ui.selection" = { bg = "#003366", fg = "#5599DD" }
"ui.linenr" = { fg = "#405060" }
"ui.linenr.selected" = { fg = "#AABBCC" }
"ui.cursor" = { bg = "#405060", fg = "D0D8E0" }
"ui.cursor.primary" = { bg = "#405060", fg = "#00DD00" }
"ui.cursorline.primary" = { bg = "#204060" }
"ui.virtual" = { fg = "#8090A0" }
"ui.virtual.ruler" = { bg = "#005050" }
"ui.virtual.indent-guide" = { fg = "#000080" }
"ui.highlight" = { bg = "#000080", fg = "#DDDD00" }
"ui.menu" = { bg = "#102030", fg = "#8090A0" }
"ui.menu.selected" = { bg = "#204060", fg = "#AACCEE" }
"ui.menu.scroll" = { bg = "#AA00AA", fg = "#6080A0" }
"ui.help" = { bg = "#102030", fg = "#6080A0" }
"ui.popup" = { bg = "#102030", fg = "#6080A0" }

warning = "#CC9900"
error = "#CC0000"
info = "#80AACC"
hint = "#80C000"

