"comment" = { fg = "comment" }
"comment.block.documentation" = { bg = "comment_doc", modifiers = ["italic"] }

"constant" = { fg = "t11" }
"function" = { fg = "t10" }
"function.method" = { fg = "t10" }
"function.macro" = { fg = "t7" }
"keyword.storage.modifier" = { fg = "t7" }
"keyword.control.import" = { fg = "t8" }
"keyword.control" = { fg = "t8" }
"keyword.function" = { fg = "t7" }
"keyword" = { fg = "t6" }
"operator" = { fg = "t8" }
"punctuation" = { fg = "t9" }
"string" = { fg = "t6", modifiers = ["italic"] }
"string.regexp" = { fg = "t6" }
"tag" = { fg = "t4" }
"type" = { fg = "t8", modifiers = ["bold"] }
"namespace" = { fg = "t6", modifiers = ["bold"] }
"variable" = { fg = "t4" }
"label" = { fg = "t4" }

"diff.plus" = { fg = "diff_plus" }
"diff.delta" = { fg = "diff_delta" }
"diff.delta.moved" = { fg = "diff_delta_moved" }
"diff.minus" = { fg = "diff_minus" }

"ui.cursor.insert" = { fg = "t2", bg = "highlight" }
"ui.cursor.select" = { fg = "t2", bg = "highlight_two" }
"ui.cursor" = { fg = "t1", bg = "highlight_three" }
"ui.cursor.match" = { fg = "highlight", bg = "selection", modifiers = ["bold"] }

"ui.linenr" = { fg = "t3", bg = "t2" }
"ui.linenr.selected" = { fg = "highlight_three", bg = "t2" }
"ui.gutter" = { bg = "t2" }

"ui.background" = { fg = "t4", bg = "t2" }
"ui.background.separator" = { fg = "t3" }
"ui.help" = { fg = "t4", bg = "t1" }
"ui.menu" = { fg = "t4", bg = "t1" }
"ui.menu.selected" = { fg = "highlight_three", bg = "t1" }
"ui.popup" = { fg = "t4", bg = "t1" }
"ui.window" = { fg = "t4" }

"ui.selection.primary" = { bg = "selection" }
"ui.selection" = { bg = "selection" }

"ui.cursorline.primary" = { bg = "t1" }

"ui.statusline" = { fg = "t4", bg = "t1" }
"ui.statusline.inactive" = { fg = "t4", bg = "t1" }
"ui.statusline.normal" = { fg = "t3", bg = "t1" }
"ui.statusline.insert" = { fg = "t3", bg = "t1" }
"ui.statusline.select" = { fg = "highlight", bg = "t4" }

"ui.text" = { fg = "t4" }
"ui.text.focus" = { fg = "highlight_three", modifiers = ["bold"] }
#
"ui.virtual.ruler" = { bg = "t1" }
"ui.virtual.indent-guide" = { fg = "t3" }
"ui.virtual.whitespace" = { fg = "t3" }

"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.hint" = { underline = { color = "display", style = "curl" } }

"error" = { fg = "error", modifiers = ["bold"] }
"warning" = { fg = "warning", modifiers = ["bold"] }
"info" = { fg = "info", modifiers = ["bold"] }
"hint" = { fg = "display", modifiers = ["bold"] }
"special" = { fg = "t7", modifiers = ["bold"] }

"markup.heading" = { fg = "t4" }
"markup.list" = { fg = "t4" }
"markup.bold" = { fg = "t4" }
"markup.italic" = { fg = "t4" }
"markup.strikethrough" = { fg = "t4", modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "t4", modifiers = ["underlined"] }
"markup.link.text" = { fg = "t4" }
"markup.quote" = { fg = "t4" }
"markup.raw" = { fg = "t4" }

[palette]
t1 = "#0e0e0d"
t2 = "#121311"
t3 = "#2b3444"
t4 = "#61586f"
t5 = "#686e73"
t6 = "#878480"
t7 = "#897dca"
t8 = "#7b89a3"
t9 = "#bcb6ba"
t10 = "#9db2b8"
t11 = "#a0c7cf"

highlight = "#ff2e5f"
highlight_two = "#0affa9"
highlight_three = "#29bbff"

black = "#000000"

selection = "#290019"

comment = "#9aacfe"
comment_doc = "#0affa9"

error = "#ff0900"
warning = "#ffbf00"
display = "#57ff89"
info = "#dad7d5"
#
