"type" = "#00D080"
"constructor" = { fg = "#90C000", modifiers = ["bold"] }
"constant" = { fg = "cyan", modifiers = ["bold"] }
"string" = "stringfg"
"string.regexp" = { fg = "#AACCEE", bg = "#205090" }
"string.special" = "blue"
"comment" = "comment"
"variable" = "#6060D0"
"label" = "#00DD99"
"keyword" = "keywordfg"
"keyword.storage" = "cyan"
"operator" = { fg = "#6080A0" }
"punctuation" = { fg = "#6080A0" }
"function" = "blue"
"function.macro" = "cyan"
"tag" = { fg = "cyan", modifiers = ["bold"] }
"attribute" = "#DDDD00"
"namespace" = { fg = "#00CCAA" }
"special" = "cyan"

"markup" = { fg = "#8090A0", modifiers = ["bold"] }
"markup.heading" = { fg = "#CCCCCC" }
"markup.list" = "purple"
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.text" = "blue"
"markup.raw" = "text"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

"ui.background" = { bg = "bg", fg = "text" }
"ui.text" = { fg = "#A0A8C0", modifiers = ["bold"] }

"ui.statusline" = { fg = "#606070", bg = "#000818" }
"ui.statusline.inactive" = { bg = "#101010", fg = "#406080" }
"ui.statusline.insert" = { bg = "#006666", fg = "#00CCCC", modifiers = ["bold"] }
"ui.statusline.normal" = { bg = "#000010", fg = "#406080", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "#006000", fg = "#00CC00", modifiers = ["bold"] }

"ui.selection" = { bg = "selectionbg", fg = "selectionfg" }
"ui.linenr" = { fg = "line-number" }
"ui.linenr.selected" = { fg = "accent" }
"ui.cursor" = { bg = "cursorbg", fg = "cursorfg" }
"ui.cursor.primary" = { bg = "cursorprimarybg", fg = "cursorprimaryfg" }
"ui.cursorline.primary" = { bg = "cursorlineprimary" }
"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "highlight" }
"ui.virtual.indent-guide" = { fg = "gray" }
"ui.highlight" = { bg = "#000080", fg = "#DDDD00" }
"ui.menu" = { bg = "#102030", fg = "#8090A0" }
"ui.menu.selected" = { bg = "#204060", fg = "#AACCEE" }
"ui.menu.scroll" = { bg = "#AA00AA", fg = "#6080A0" }
"ui.help" = { bg = "#102030", fg = "#6080A0" }
"ui.popup" = { bg = "#102030", fg = "#6080A0" }

warning = "yellow"
error = "error"
info = "blue"
hint = "purple"

[palette]
bg = "#001020"
text = "#a0a8c0"

white = "#eeffff"
green = "#c3e88d"
yellow = "#FFFF00"
blue = "#82aaff"
red = "#00FFFF"
purple = "#FFFF00"
orange = "#00FF00"
cyan = "#80C0E0"
gray = "#717cb4"
error = "#ff5370"

disabled = "#464b5d"

accent = "#84ffff"

active = "#1a1c25"
highlight = "#1f2233"

comment = "#405060"

selection = "#1f2233"
selectionbg = "#000000"
selectionfg = "#EEEE00"

line-number = "#3b3f51"

cursorbg = "#880000"
cursorfg = "#FF0000"
cursorprimarybg = "#464B5D"
cursorprimaryfg = "#EEEEEE"
cursorlineprimary = "#442200"
highlightbg = "#CC0000"
highlightfg = "#AACCEE"
keywordfg = "#7070C0"
stringfg = "#8080A0"
