kitty_mod					ctrl+shift

foreground					#808080
background					#000000
cursor						#a00000

# font_family					SF Mono
# font_family					Fixedsys
# font_family					Monospace
# font_family					Consolas
font_size					12.0

font_family      			family='SF Mono' style=Semibold
bold_font        			family='SF Mono' postscript_name=SFMono-Bold
italic_font      			auto
bold_italic_font 			auto

tab_separator				" "
tab_bar_min_tabs			1
tab_bar_style				separator
tab_bar_edge				top
tab_bar_margin_width		10.0
tab_bar_margin_height		1.0 1.0
tab_title_template			"{index}"
active_tab_title_template	"{index}"
active_tab_foreground   	#AAA
active_tab_background   	#404040
selection_foreground		#aabbcc
selection_background		#224477
inactive_tab_foreground 	#888
inactive_tab_background 	#282828
active_tab_font_style   	bold
inactive_tab_font_style 	normal
tab_activity_symbol			none
disable_ligatures			always
cursor_shape				beam

window_padding_width		0 0 24 800
scrollback_lines 20000

map ctrl+v					paste_from_clipboard
map ctrl+l					combine : clear_terminal scrollback active : clear_terminal to_cursor active
map kitty_mod+f5			load_config_file


